name: Format_Build_Test_Docker

on:
  push:
    branches:
      - pro_1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Get current time
       uses: 1466587594/get-current-time@v2
       id: current-time
       with:
         format: YYYYMMDD-HH
         utcOffset: "+08:00"       
      - uses: actions/checkout@v2
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          # Enable linters
          eslint: true
     
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command

      - name: Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test # will run `yarn test` command

      - name: Create the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: mbeheiry
          password: Safia90&&
          repository: mbeheiry/testing_1
          tags: V-${{ steps.current-time.outputs.day }}-${{ steps.current-time.outputs.month }}-${{ steps.current-time.outputs.year }}-${{ steps.current-time.outputs.hour }}-${{ steps.current-time.outputs.minute }}
          tag_with_ref: false